language: python

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.73.0/hugo_extended_0.73.0_Linux-64bit.deb
  - sudo dpkg -i hugo_extended_0.73.0_Linux-64bit.deb

script:
  - hugo

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local-dir: public
  repo: zivkovic-lab/zivkovic-lab.github.io
  target_branch: master
  on:
    branch: master